### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by TravisWilder** [DirectoryTree/LdapRecord#551]
**Environment:**

 - LDAP Server Type: ActiveDirectory
 - PHP Version: PHP 8.1.2
 - directorytree/ldaprecord            v2.19.3  A
 - directorytree/ldaprecord-laravel    v2.7.2  

**Describe the bug:**

I run during the night some AD Checks and I get regular the error below.
When I run the same test later the day again it works fine
I was not able yet to catch the exception, so the tasks stops and many users are not checked

The Command in my code (row 23):
$uac = new AccountControl($account->getFirstAttribute('userAccountControl'));

**Error Log**
```
production.ERROR: Object of class LdapRecord\Models\Attributes\AccountControl could not be converted to int {"exception":"[object] (ErrorException(code: 0): Object of class LdapRecord\\Models\\Attributes\\AccountControl could not be converted to int at C:\\WebSites\\web\\vendor\\directorytree\\ldaprecord\\src\\Models\\Attributes\\AccountControl.php:495)
[stacktrace]
#0 C:\\WebSites\\web\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Bootstrap\\HandleExceptions.php(266): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 C:\\WebSites\\web\\vendor\\directorytree\\ldaprecord\\src\\Models\\Attributes\\AccountControl.php(495): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}()
#2 C:\\WebSites\\web\\vendor\\directorytree\\ldaprecord\\src\\Models\\Attributes\\AccountControl.php(131): LdapRecord\\Models\\Attributes\\AccountControl->extractFlags()
#3 C:\\WebSites\\web\\vendor\\directorytree\\ldaprecord\\src\\Models\\Attributes\\AccountControl.php(68): LdapRecord\\Models\\Attributes\\AccountControl->apply()
#4 C:\\WebSites\\web\\app\\Library\\ActiveDirectory\\Mails\\Password.php(23): LdapRecord\\Models\\Attributes\\AccountControl->__construct()
```

Any help is appricated

**Comment by TravisWilder** [comment]
Hello
My Custom User Model extending LdapRecord\Models\ActiveDirectory\User but is not overwriting the userAccountControl accessor or has function with the same name.
These are the only functions in the model which uses AccountControl

```
        public function uac() 
	{
		if ($this->uac == null ) $this->uac =  new AccountControl(
			$this->getFirstAttribute('userAccountControl')
		); 
		return $this->uac;
	}
        public function isDisabled()
	{
		return $this->uac()->has(AccountControl::ACCOUNTDISABLE);
	}
       public function setDisabled()
	{
		$this->uac()->accountIsDisabled();
		$this->userAccountControl = $this->uac;
		return $this;
	}
```

the function which is Failing

```
    $uac = new AccountControl($account->getFirstAttribute('userAccountControl'));
    $type = $account->getFirstAttribute('AccType');
```

Last night the issue did not happend again. I added detailed logging. To review the user object which failed.
If it happens again I will give an update

**Comment by TravisWilder** [comment]
Is still happening - I assume currently that this happens if the UAC was altered on the user object before and than I read it again.
Like I do something like
```
$user->userAccountControl = (new AccountControl)->accountIsNormal();

$user->save();
```
and then on the same object a
```
$uac = new AccountControl($account->getFirstAttribute('userAccountControl'));
```
Would then not be the Object given to new AccountControl instead of the int?
