### ISSUE TITLE
[Bug] Constraint violation when attempting to create user with password over SSL

### ISSUE THREAD

**Issue by DarkestSoul1992** [DirectoryTree/LdapRecord#574]
**Environment:**
 - LDAP Server Type: ActiveDirectory
 - PHP Version: 8.2.3

**Describe the bug:**
Add: Constraint violation in \vendor\directorytree\ldaprecord\src\Ldap.php:316

        `require $_SERVER['DOCUMENT_ROOT'] . '/vendor/autoload.php';
	
	$connection = new LdapRecord\Connection([
		// Mandatory Configuration Options
		'hosts'         		 => ['xxxx.wolfnet.local'],
		'base_dn'          => 'dc=wolfnet,dc=local',
		'username'         => 'xxxx@wolfnet.local',
		'password'         => 'xxxx',

		// Optional Configuration Options
		'port'             => 636,
		'use_ssl'          => true,
		'version'          => 3,
		'timeout'          => 5,
		'follow_referrals' => false,
	]);
	$connection->connect();
	// Add the connection to the container:
	\LdapRecord\Container::getInstance()->add($connection);
	$user = (new LdapRecord\Models\ActiveDirectory\User)->inside('dc=wolfnet,dc=local');
	$user->cn = $name;
	$user->unicodePwd = $password;
	$user->samaccountname = $username;
	$user->userPrincipalName = $username . '@wolfnet.local';
	$user->save();
	// Sync the created users attributes.
	$user->refresh();
	// Enable the user.
	$user->userAccountControl = 512;
	try {
		$user->save();
	} catch (\LdapRecord\LdapRecordException $e) {
		echo 'Failed saving user.';
		exit();
	}
	echo 'AD User created!';`

Throws this error:
`Fatal error: Uncaught ErrorException: ldap_add(): Add: Constraint violation in C:\inetpub\wwwroot\vendor\directorytree\ldaprecord\src\Ldap.php:316 Stack trace: #0 [internal function]: LdapRecord\Ldap->LdapRecord\{closure}() #1 C:\inetpub\wwwroot\vendor\directorytree\ldaprecord\src\Ldap.php(316): ldap_add() #2 C:\inetpub\wwwroot\vendor\directorytree\ldaprecord\src\HandlesConnection.php(171): LdapRecord\Ldap->LdapRecord\{closure}() #3 C:\inetpub\wwwroot\vendor\directorytree\ldaprecord\src\Ldap.php(315): LdapRecord\Ldap->executeFailableOperation() #4 C:\inetpub\wwwroot\vendor\directorytree\ldaprecord\src\Query\Builder.php(1851): LdapRecord\Ldap->add() #5 C:\inetpub\wwwroot\vendor\directorytree\ldaprecord\src\Connection.php(426): LdapRecord\Query\Builder->LdapRecord\Query\{closure}() #6 C:\inetpub\wwwroot\vendor\directorytree\ldaprecord\src\Connection.php(366): LdapRecord\Connection->runOperationCallback() #7 C:\inetpub\wwwroot\vendor\directorytree\ldaprecord\src\Query\Builder.php(1850): LdapRecord\Connection->run() #8 C:\inetpub\wwwroot\vendor\directorytree\ldaprecord\src\Models\Model.php(1170): LdapRecord\Query\Builder->insert() #9 C:\inetpub\wwwroot\vendor\directorytree\ldaprecord\src\Models\Model.php(1130): LdapRecord\Models\Model->performInsert() #10 C:\inetpub\wwwroot\admin\add_user.php(40): LdapRecord\Models\Model->save() #11 {main} Next LdapRecord\LdapRecordException: ldap_add(): Add: Constraint violation in C:\inetpub\wwwroot\vendor\directorytree\ldaprecord\src\LdapRecordException.php:26 Stack trace: #0 C:\inetpub\wwwroot\vendor\directorytree\ldaprecord\src\HandlesConnection.php(184): LdapRecord\LdapRecordException::withDetailedError() #1 C:\inetpub\wwwroot\vendor\directorytree\ldaprecord\src\Ldap.php(315): LdapRecord\Ldap->executeFailableOperation() #2 C:\inetpub\wwwroot\vendor\directorytree\ldaprecord\src\Query\Builder.php(1851): LdapRecord\Ldap->add() #3 C:\inetpub\wwwroot\vendor\directorytree\ldaprecord\src\Connection.php(426): LdapRecord\Query\Builder->LdapRecord\Query\{closure}() #4 C:\inetpub\wwwroot\vendor\directorytree\ldaprecord\src\Connection.php(366): LdapRecord\Connection->runOperationCallback() #5 C:\inetpub\wwwroot\vendor\directorytree\ldaprecord\src\Query\Builder.php(1850): LdapRecord\Connection->run() #6 C:\inetpub\wwwroot\vendor\directorytree\ldaprecord\src\Models\Model.php(1170): LdapRecord\Query\Builder->insert() #7 C:\inetpub\wwwroot\vendor\directorytree\ldaprecord\src\Models\Model.php(1130): LdapRecord\Models\Model->performInsert() #8 C:\inetpub\wwwroot\admin\add_user.php(40): LdapRecord\Models\Model->save() #9 {main} Next LdapRecord\Exceptions\ConstraintViolationException: ldap_add(): Add: Constraint violation in C:\inetpub\wwwroot\vendor\directorytree\ldaprecord\src\LdapRecordException.php:26 Stack trace: #0 C:\inetpub\wwwroot\vendor\directorytree\ldaprecord\src\Connection.php(409): LdapRecord\LdapRecordException::withDetailedError() #1 C:\inetpub\wwwroot\vendor\directorytree\ldaprecord\src\Connection.php(368): LdapRecord\Connection->getExceptionForCauseOfFailure() #2 C:\inetpub\wwwroot\vendor\directorytree\ldaprecord\src\Query\Builder.php(1850): LdapRecord\Connection->run() #3 C:\inetpub\wwwroot\vendor\directorytree\ldaprecord\src\Models\Model.php(1170): LdapRecord\Query\Builder->insert() #4 C:\inetpub\wwwroot\vendor\directorytree\ldaprecord\src\Models\Model.php(1130): LdapRecord\Models\Model->performInsert() #5 C:\inetpub\wwwroot\admin\add_user.php(40): LdapRecord\Models\Model->save() #6 {main} thrown in C:\inetpub\wwwroot\vendor\directorytree\ldaprecord\src\LdapRecordException.php on line 26`

**Comment by stevebauman** [comment]
Hi @DarkestSoul1992,

A constraint violation usually means the password you've set doesn't meet the requirements of the domain.

Try dumping additional details of the error by accessing them from the exception:

```php
try {
    // ...
} catch (\LdapRecord\LdapRecordException $ex) {
    // Failed changing password. Get the last LDAP
    // error to determine the cause of failure.
    $error = $ex->getDetailedError();

    echo $error->getErrorCode();
    echo $error->getErrorMessage();
    echo $error->getDiagnosticMessage();
}
```

**Comment by stevebauman** [comment]
Closing due to inactivity.
