### ISSUE TITLE
Can't auth with Laravel Breeze with plain auth or database auth

### ISSUE THREAD

**Issue by Do-Charlie** [DirectoryTree/LdapRecord#706]
**Environment:** 

PHP Version: [ 8.1]
Laravel Version : [10.48]
LdapRecord-Laravel : [v3]

**Describe the bug:** 
I follow the steps from the documentation.
When i'm using my credentials in .env file , the command `php artisan ldap:test` is working but when i'm typing my credientials in the login page from breeze , the authentication is not made. 
There is my logs : 
```
[2024-04-04 09:28:49] local.INFO: LDAP (ldap://192.168.253.2:389) - Operation: Binding - Username:   
[2024-04-04 09:28:49] local.INFO: LDAP (ldap://192.168.253.2:389) - Operation: Bound - Username:   
[2024-04-04 09:28:49] local.INFO: LDAP (ldap://192.168.253.2:389) - Operation: Binding - Username:   
[2024-04-04 09:28:49] local.INFO: LDAP (ldap://192.168.253.2:389) - Operation: Bound - Username:   
[2024-04-04 09:28:49] local.ERROR: ldap_search(): Search: Operations error {"exception":"[object] (LdapRecord\\LdapRecordException(code: 2): ldap_search(): Search: Operations error at C:\\laragon_www\\ldap2\\vendor\\directorytree\\ldaprecord\\src\\LdapRecordException.php:19)
[stacktrace]
#0 C:\\laragon_www\\ldap2\\vendor\\directorytree\\ldaprecord\\src\\HandlesConnection.php(197): LdapRecord\\LdapRecordException::withDetailedError(Object(ErrorException), Object(LdapRecord\\DetailedError))
#1 C:\\laragon_www\\ldap2\\vendor\\directorytree\\ldaprecord\\src\\Ldap.php(208): LdapRecord\\Ldap->executeFailableOperation(Object(Closure))
```

I don't know why but I think that informations from my login form is not set in the  authentication function for ldap. 
I checked in LoginRequest.php and my mail and passworld is well received from my Login page. When i add my credentials directly into the .env file , i don't have anymore the "ldap_search()" error. 

There is my configuration : 
**LoginRequest.php**

```
public function authenticate(): void
    {

        $this->ensureIsNotRateLimited();

        $credentials = [
            'mail' => $this->email,
            'password' => $this->password,
        ];
            
   
        
        if (! Auth::attempt($credentials, $this->filled('remember'))) {
            RateLimiter::hit($this->throttleKey());

            throw ValidationException::withMessages([
                'username' => trans('auth.failed'),
            ]);
        }

        RateLimiter::clear($this->throttleKey());
    }

```

**auth.php**

```
   'providers' => [
        // ...
    
        'users' => [
            'driver' => 'ldap',
            'model' => LdapRecord\Models\OpenLDAP\User::class,
            'rules' => [],
            'scopes' => [],
            'database' => [
                'model' => App\Models\User::class,
                'sync_passwords' => false,
                'sync_attributes' => [
                    'name' => 'cn',
                    'email' => 'mail',
                ],
            ],
        ],
    ],

```

**Comment by stevebauman** [comment]
Hi @Do-Charlie,

Operations error typically indicates a malformed `base_dn` in your LDAP configuration. Please check that this is correct.

If you're sure it's correct and please post your LDAP config here (with sensitive details omitted), and I'll re-open this issue.

Thanks!

**Comment by Tamas-hi** [comment]
I have exactly the same problem. base_dn is correct in my case. If I do a simple basic auth from a controller, that works:

$connection = Container::getDefaultConnection();
if ($connection->auth()->attempt('username@xyz.com', 'password')) {
    // success
}

But doing an Auth::attempt results in this ldap_search() error as the OP said. Still trying to debug what is going on, but any help is appreciated. @Do-Charlie  maybe you found a solution since then?

**Comment by Do-Charlie** [comment]
Hello , I also had a correct base_dn and still have the issue,  I was using Laravel Breeze for the authentification , what I did was I changed "LoginRequest.php" file and  used  LdapRecord for PHP instead of LdapRecord for Laravel.  If an attempt is successful the user is manually authentificated.

     $connection = new Connection([
                'hosts' => [env('LDAP_HOST')],
                'username' => $email,
                'password' => $password,
                'base_dn' => env('LDAP_BASE_DN'),
            ]);
        }

        try {
        //Tentative de connexion avec la configuration LDAP
            $connection->connect();
        } catch (\LdapRecord\Auth\BindException $e) {
              throw ValidationException::withMessages([
                'email' => 'Erreur authentification LDAP ',
            ]);
        } catch (\Exception $e) {
            throw ValidationException::withMessages([
                'email' => trans('auth.failed'),
            ]);
        }
...
        Auth::login($user, $this->boolean('remember'));


But I didn't found a solution for LdapRecord integrated with Laravel.

**Comment by Tamas-hi** [comment]
> Hello , I also had a correct base_dn and still have the issue, I was using Laravel Breeze for the authentification , what I did was I changed "LoginRequest.php" file and used LdapRecord for PHP instead of LdapRecord for Laravel. If an attempt is successful the user is manually authentificated.
> 
> ```
>  $connection = new Connection([
>                 'hosts' => [env('LDAP_HOST')],
>                 'username' => $email,
>                 'password' => $password,
>                 'base_dn' => env('LDAP_BASE_DN'),
>             ]);
>         }
> 
>         try {
>         //Tentative de connexion avec la configuration LDAP
>             $connection->connect();
>         } catch (\LdapRecord\Auth\BindException $e) {
>               throw ValidationException::withMessages([
>                 'email' => 'Erreur authentification LDAP ',
>             ]);
>         } catch (\Exception $e) {
>             throw ValidationException::withMessages([
>                 'email' => trans('auth.failed'),
>             ]);
>         }
>        
>         Auth::login($user, $this->boolean('remember'));
> ```
> 
> But I didn't found a solution for LdapRecord integrated with Laravel.

Thank you, appreciate the fast help. I'll give it a go to debug it and get back here if I find anything... 

So far what I see is that inside the bind function in Ldap.php file does not get the dn, and neither the password, both are null.

```
public function bind(?string $dn = null, ?string $password = null, ?array $controls = null): LdapResultResponse
    {
        dd($dn); // null
        dd($password); // null

        /** @var \LDAP\Result $result */
        $result = $this->executeFailableOperation(function () use ($dn, $password, $controls) {
            return ldap_bind_ext($this->connection, $dn, $password ? html_entity_decode($password) : null, $controls);
        });

        $response = $this->parseResult($result);

        $this->handleBindResponse($response);

        return $response;
    }
```

**Comment by stevebauman** [comment]
@Tamas-hi 

>  I don't understand yet why it is necessary when I set the sync_passwords to false in my auth.php, but at least it works now.

Even if you have `sync_passwords` set to `false` in your LdapRecord configuration, the assumption is made that you have not modified the default Laravel `users` database table migration which does not allow `null` to be inserted into the column:

https://github.com/laravel/laravel/blob/6ebd9fed8a1724464e9c1138d94c882d12dfd61b/database/migrations/0001_01_01_000000_create_users_table.php#L19

If you would like to disable setting this column completely, you must set the `passowrd_column` configuration option to `false`, as shown in the documentation:

https://ldaprecord.com/docs/laravel/v3/auth/database/configuration/#sync-password-column

> You can also set the value to false if your database table does not have any password column at all:

> ```php
> 'providers' => [
>     // ...
> 
>     'users' => [
>         // ...
>         'database' => [
>             // ...
>             'password_column' => false,
>         ],
>     ],
> ],
> ```

**Comment by Tamas-hi** [comment]
Appreciate the support. Sadly I realised now, that I just filled out my LDAP_USERNAME and LDAP_PASSWORD env variable yesterday during, and that is why it seemed to me it was working, but in reality, it still isn't. 

I am still getting the **ldap_search(): Search: Operations error** with the stack trace I provided above.

My setup now (migration contains the password once again):

1. ldap.php

'connections' => [

        'default' => [
            'hosts' => [env('LDAP_HOST', '<correct host>')],
            'username' => env('LDAP_USERNAME', ''),
            'password' => env('LDAP_PASSWORD', ''),
            'port' => env('LDAP_PORT', 636),
            'base_dn' => env('LDAP_BASE_DN', '<correct base dn>'),
            'timeout' => env('LDAP_TIMEOUT', 5),
            'use_ssl' => env('LDAP_SSL', true),
            'use_tls' => env('LDAP_TLS', true),
            'use_sasl' => env('LDAP_SASL', false),
            'sasl_options' => [
                // 'mech' => 'GSSAPI',
            ],
        ],

    ],
2. auth.php
```
'providers' => [
        'users' => [
            'driver' => 'ldap',
            'model' => LdapRecord\Models\ActiveDirectory\User::class,
            'rules' => [],
            'scopes' => [],
            'database' => [
                'model' => App\Models\User::class,
                'sync_attributes' => [
                    'name' => 'cn',
                    'email' => 'mail',
                ],
            ],
        ],
    ],
```
3. LoginRequest.php

```
public function authenticate()
    {
        $this->ensureIsNotRateLimited();

        $credentials = [
            'mail' => $this->email, // correct email
            'password' => $this->password, // correct password
        ];

        if (Auth::attempt($credentials)) {
            $user = Auth::user();

            dd($user);
        
            return redirect('/dashboard')->with([
                'message' => "Welcome back, {$user->name}"
            ]);
        }

        dd('not successfull');

        RateLimiter::clear($this->throttleKey());
    }
```

**Comment by stevebauman** [comment]
@Tamas-hi Happy to help!

Ok, I'll give this a shot tomorrow with OpenLDAP and Laravel Breeze to see if I can replicate this.

**Comment by Tamas-hi** [comment]
Thank you!

In the meantime, I am happy to say that I think I have finally found a 'workaround' for my problem.   

The problem I think still is that we never use the $credentials inside the UserRepository->findByCredentials() method during execution, so I had to create my own Repository (really great feature that we have a chance to extend it - https://ldaprecord.com/docs/laravel/v3/extending)

My own UserRepository:

```
public function findByCredentials(array $credentials = []): ?Model
    {
        if (empty($credentials)) {
            return null;
        }

        $query = $this->query();

        $existingConfig = $query->getConnection()->getConfiguration()->all(); // Get current config

        $extraFields = [ // set the extraFields manually - this is the crucial part. Without it, username and password remains empty.  Also I need to use userprincipalname in my case because of Active Directory I believe but that should not be relevant to the problem.
            'username' => $credentials['userprincipalname'],
            'password' => $credentials['password']
        ];

        $newConfig = array_merge($existingConfig, $extraFields); // Create new config

        $newConnection = new Connection($newConfig); // Create new connection

        $query->setConnection($newConnection); // update query connection - now we have all the necessary credentials

        foreach ($credentials as $key => $value) {
            if (Str::contains($key, $this->bypassCredentialKeys)) {
                continue;
            }

            if (is_array($value) || $value instanceof Arrayable) {
                $query->whereIn($key, $value);
            } else {
                $query->where($key, $value);
            }
        }

        if (is_null($user = $query->first())) {
            return null;
        }

        event(new DiscoveredWithCredentials($user));

        return $user;
    }

```
That works for now, but maybe I am still missing something and this should not be necessary.

**Comment by stevebauman** [comment]
Oh hold on, I missed this in the original post:

> When i add my credentials directly into the .env file , i don't have anymore the "ldap_search()" error.

> if I leave my environment variables empty (which of course I do, because this is coming from the user). Therefore everything after this step fails, because we can't connect to the server, we can't query data.

This is intended. You can't use LdapRecord-Laravel without configuring a service account in your `.env` file. This is not supported.

LdapRecord-Laravel **must** have access to be able to locate the user prior to the authentication attempt, this is because the authentication driver (as you've discovered) attempts to locate the user prior to authentication using the LDAP attribute of your choice.

If this exception is only occurring when you have an empty username or password, than this is intended behaviour.

**Comment by Tamas-hi** [comment]
> Oh hold on, I missed this in the original post:
> 
> > When i add my credentials directly into the .env file , i don't have anymore the "ldap_search()" error.
> 
> > if I leave my environment variables empty (which of course I do, because this is coming from the user). Therefore everything after this step fails, because we can't connect to the server, we can't query data.
> 
> This is intended. You can't use LdapRecord-Laravel without configuring a service account in your `.env` file. Unless you have anonymous binding enabled on your LDAP server (which allows connecting without a username and password), it is not supported to have no username and password configured for the LDAP connection.
> 
> LdapRecord-Laravel **must** have access to be able to locate the user prior to the authentication attempt, this is because the authentication driver (as you've discovered) attempts to locate the user prior to authentication using the LDAP attribute of your choice.
> 
> If this exception is only occurring when you have an empty username or password, then this is intended behaviour.
> 
> Was there something in the documentation that may have mislead you to this conclusion? If so, let me know and I can patch it 👍

Thanks for the quick checking, I am pretty sure this is the explanation, and OP and I had the some problem. I think this is just how it made sense to us, that in this case only the 'user credentials' are enough, and there is no need for a service account.

In my case, I think anyonymus binding is even enabled, because I can connect without .env credentials using the `php artisan ldap:test` command. Searching though seems to be disabled, but I will confirm that later and edit it here.

The docs is really good, just a thought from my side:

- https://ldaprecord.com/docs/laravel/v3/auth/database/logging-in - Would it make sense to include a purple info box here thats warns you to make sure your env variables are configured including a valid username and password different than the credentials present here?

I will add a service account then. Issue can be closed from my side. 🙏
